name: send msg to feishu
# 触发条件
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
  push:
    branches: [ "master" ]

# 设置权限
permissions:
  contents: write

# 设置上海时区
env:
  TZ: Asia/Shanghai

jobs:
  run_task:
    name: send img to feishu
    runs-on: ubuntu-latest
    env:
      GEMINI_FLASH_API_KEY=$GEMINI_FLASH_API_KEY

    steps:
      - name: 获取环境变量
        run: echo $GEMINI_FLASH_API_KEY

      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: |
          pip3 install -r requirements.txt

      - name: exec request
        run: |
          python main.py
        env:
          GEMINI_FLASH_API_KEY=$GEMINI_FLASH_API_KEY
      
      - name: output time
        run: |
          echo `date +'%Y-%m-%d %H:%M:%S'`

