name: send msg to feishu
# 触发条件
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
  push:
    branches: [ "master" ]


# 设置权限
permissions:
  contents: write

# 设置上海时区
env:
  TZ: Asia/Shanghai
  
jobs:
  run_task:
    name: send img to feishu
    runs-on: ubuntu-latest

    steps:
      - name: 获取环境变量
        run: echo ${{ secrets.FEISHU_APP_ID }}

